import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: "class",
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#6a75ff",
        "secondary-fixed-dim": "#d0bcff",
        error: "#ba1a1a",
        "on-background": "#0b1c30",
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#00026c",
        "primary-container": "#131b2e",
        "secondary-fixed": "#e9ddff",
        "inverse-primary": "#bec6e0",
        "tertiary-fixed-dim": "#bec2ff",
        outline: "#76777d",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#45464d",
        "on-primary-container": "#7c839b",
        background: "#f8f9ff",
        "on-tertiary-fixed-variant": "#232cc6",
        "on-secondary-fixed-variant": "#5500cb",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed": "#23005c",
        "on-surface": "#0b1c30",
        secondary: "#6c2ce6",
        "surface-container-high": "#dce9ff",
        "inverse-surface": "#213145",
        tertiary: "#000000",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#854eff",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "tertiary-container": "#00026c",
        "on-secondary-container": "#fffbff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed": "#dae2fd",
        primary: "#000000",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e0e0ff",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container": "#e5eeff",
        
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        base: "4px",
        lg: "24px",
        xs: "4px",
        "margin-desktop": "64px",
        xl: "32px",
        gutter: "24px",
        md: "16px",
        xxl: "48px",
        "margin-mobile": "16px",
        "max-width": "1280px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
export default config